services:
  postgres:
    hostname: postgres
    image: debezium/postgres:16-alpine
    build: ./docker/postgres
    ports:
      - "5432:5432"
    environment:
#      POSTGRES_DB: tkpm
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./docker/postgres/postgresql.conf.sample:/usr/share/postgresql/postgresql.conf.sample
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
#      - postgres:/var/lib/postgresql/data
    command: postgres -c 'max_connections=500'
    networks:
      - flask-network

  pgadmin:
    hostname: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    depends_on:
      - postgres
    ports:
      - "5050:5050"
    networks:
      - flask-network

  redis:
    hostname: redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    networks:
      - flask-network

#  api:
#    image: flask-api
#    build: .
#    ports:
#      - "5000:5000"
#    depends_on:
#      - postgres
#    networks:
#      - flask-network

volumes:
  postgres:

networks:
  flask-network:
    driver: bridge